#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "You must run this with superuser priviliges.  Try \"sudo ./install\"" 2>&1
    exit 1
else
    echo "Installing Jankun..."
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo cp jankun /usr/local/bin/jankun
    sudo cp updater /usr/local/bin/jankun-updater
elif [[ "$OSTYPE" == "darwin"* ]]; then
    sudo cp jankun_mac /usr/local/bin/jankun
    sudo cp updater_mac /usr/local/bin/jankun-updater
fi
sudo chmod +x /usr/local/bin/jankun
sudo chmod +x /usr/local/bin/jankun-updater

echo "Jankun installed ! cd to your project and type jankun to start :)"
